# Generated by Django 5.1.2 on 2024-10-12 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('command', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('current_temp', models.CharField(max_length=255, verbose_name='Текущая температра')),
                ('feels', models.CharField(max_length=255, verbose_name='Ощущаемая температура')),
                ('desc', models.CharField(max_length=255, verbose_name='Описание')),
                ('hum', models.CharField(max_length=255, verbose_name='Влажность')),
                ('wind', models.CharField(max_length=255, verbose_name='Скорость ветра')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.profiletelegram')),
            ],
        ),
    ]
