# Generated by Django 5.1.2 on 2024-10-12 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bot',
            new_name='InfoBot',
        ),
    ]
