# Generated by Django 5.1.2 on 2024-10-13 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_bot_infobot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infobot',
            name='command',
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.profiletelegram')),
            ],
        ),
    ]
