# Generated by Django 5.1.2 on 2024-10-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_infobot_command_command'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Command',
            new_name='CommandBot',
        ),
    ]
